// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListMarkdownFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ParseOutline(arg1:string):Promise<Array<main.OutlineItem>>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;
