// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFolderFiles(arg1) {
  return window['go']['main']['App']['ListFolderFiles'](arg1);
}

export function ListFolderFilesRecursive(arg1) {
  return window['go']['main']['App']['ListFolderFilesRecursive'](arg1);
}

export function ListMarkdownFiles(arg1) {
  return window['go']['main']['App']['ListMarkdownFiles'](arg1);
}

export function ParseMarkdown(arg1) {
  return window['go']['main']['App']['ParseMarkdown'](arg1);
}

export function ParseOutline(arg1) {
  return window['go']['main']['App']['ParseOutline'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
