// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialFilePath():Promise<string>;

export function ListFolderFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ListFolderFilesRecursive(arg1:string):Promise<Array<main.FileInfo>>;

export function ListMarkdownFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ParseMarkdown(arg1:string):Promise<string>;

export function ParseOutline(arg1:string):Promise<Array<main.OutlineItem>>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;
