// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMarkdownFiles(arg1) {
  return window['go']['main']['App']['ListMarkdownFiles'](arg1);
}

export function ParseOutline(arg1) {
  return window['go']['main']['App']['ParseOutline'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
